name: Yarn CI (Device)

on: [push]

jobs:
  lint-device:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: './device/src/miscs/serviceAccountCredentials.json'
          FILE_DATA: '{ "api_key": "", "auth_domain": "", "databaseURL": "" }'
      - name: yarn install, lint
        run: |
          yarn install
          yarn lint
        working-directory: ./device
