name: Yarn CI (Frontend)

on: [push, pull_request]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, lint
        run: |
          yarn install
          yarn lint
          yarn eslint
        working-directory: ./frontend 