name: ReviewDog
on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        working-directory: ./frontend 
        uses: reviewdog/action-eslint@v1
        with: 
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{js,ts,vue}'
